name = "landingpage"
compatibility_date = "2023-01-01"

[site]
bucket = "."

[build]
command = ""
upload.format = "directory"
output_directory = "."

[env.production]
routes = [{pattern = "*", zone_name = "landingpage"}]
